# Generated by Django 2.1.1 on 2020-09-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_bankbranch_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankbranch',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='bank_id',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='district',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='ifsc',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='state',
        ),
    ]
