# Generated by Django 3.0.8 on 2020-09-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_auto_20200927_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
