# Generated by Django 3.0.8 on 2020-09-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_imageupload_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='name',
            field=models.CharField(blank=True, max_length=49, null=True),
        ),
    ]
